# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master", "v4" ]
  pull_request:
    branches: [ "master", "v4" ]

defaults:
  run:
    working-directory: ./python

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4.1
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
        cache-dependency-path: |
          ./python/pdm.lock

    - name: Install dependencies
      run: pdm install

    - name: Run tests
      run: |
        pdm run -v python -m unittest discover -s tests
